# Generated by Django 3.1.4 on 2020-12-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.URLField(default='', max_length=255),
        ),
    ]
